//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfATCApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int IDDistrict { get; set; }
        public int Numder { get; set; }
    
        public virtual District District { get; set; }
    }
}
