//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfATCApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberPhone
    {
        public int ID { get; set; }
        public string PairedNumber { get; set; }
        public decimal Debt { get; set; }
        public System.DateTime InstallationDate { get; set; }
    }
}
