//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfATCApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public int ID { get; set; }
        public string IDNumderPhone { get; set; }
        public string Firstname { get; set; }
        public int IDBlocker { get; set; }
        public string Note { get; set; }
    
        public virtual Blocker Blocker { get; set; }
    }
}
